# Generated by Django 5.2.1 on 2025-05-21 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='terreno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField()),
                ('propietario', models.CharField()),
                ('ubicación', models.CharField()),
                ('tamaño', models.FloatField()),
            ],
        ),
    ]
