# Generated by Django 5.2.1 on 2025-05-21 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='requerimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField()),
                ('tipo_de_terreno', models.CharField()),
                ('Fecha_de_siembra', models.DateField()),
            ],
        ),
    ]
