# Generated by Django 5.2.1 on 2025-05-21 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='sensor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField()),
                ('descripcion', models.CharField()),
                ('ubicacion', models.CharField()),
                ('fecha_instal', models.DateTimeField()),
            ],
        ),
    ]
