# Generated by Django 5.2.1 on 2025-05-21 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='cultivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField()),
                ('fecha_siembra', models.DateField()),
                ('fecha_cosecha', models.DateField()),
                ('nombre_terreno', models.CharField()),
            ],
        ),
    ]
