# Generated by Django 5.2.2 on 2025-06-05 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='informe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField()),
                ('informacion', models.CharField()),
                ('generacion', models.DateField()),
                ('alerta', models.BooleanField()),
            ],
        ),
    ]
